# Generated by Django 2.0.2 on 2018-03-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkamenity',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_amenities', to='parks.Park'),
        ),
    ]
