# Generated by Django 2.0.2 on 2018-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_auto_20180304_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='district',
            field=models.IntegerField(null=True),
        ),
    ]
