# Generated by Django 2.0.2 on 2018-03-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_auto_20180304_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='shape_length',
            field=models.FloatField(null=True),
        ),
    ]
